name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Enable Corepack
      run: corepack enable
    
    - name: Setup Yarn cache
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --immutable
    
    - name: TypeScript type check
      run: yarn tsc:check || echo "Type check warnings - continuing build"
    
    - name: Build package
      run: yarn build
    
    - name: Run tests
      run: yarn test
    
    - name: Run lint
      run: yarn lint
    
    - name: Check package can be packed
      run: yarn pack --dry-run