name: Publish to NPM

on:
  push:
    branches: [ main, master ]
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        registry-url: 'https://registry.npmjs.org'
    
    - name: Enable Corepack
      run: corepack enable
    
    - name: Setup Yarn cache
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: yarn install --immutable
    
    - name: Run type check
      run: yarn tsc --noEmit
    
    - name: Build package
      run: yarn build
    
    - name: Run tests
      run: yarn test --passWithNoTests
    
    - name: Auto-increment version
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          # Auto-increment patch version for pushes to main
          npm version patch --no-git-tag-version
        fi
    
    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Create GitHub deployment
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createDeployment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.sha,
            environment: 'npm',
            description: 'Published to NPM registry'
          })